"""Add feature store and behavior snapshots

Revision ID: 8e2e28097b46
Revises: fefd87640668
Create Date: 2026-07-25 17:13:09.426874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2e28097b46'
down_revision: Union[str, None] = 'fefd87640668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('window_size', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_snapshots_entity_id'), 'behavior_snapshots', ['entity_id'], unique=False)
    op.create_index(op.f('ix_behavior_snapshots_entity_type'), 'behavior_snapshots', ['entity_type'], unique=False)
    op.create_index(op.f('ix_behavior_snapshots_timestamp'), 'behavior_snapshots', ['timestamp'], unique=False)
    op.create_index(op.f('ix_behavior_snapshots_window_size'), 'behavior_snapshots', ['window_size'], unique=False)
    op.create_table('asset_behavior_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('window_size', sa.String(length=10), nullable=False),
    sa.Column('access_frequency', sa.Float(), nullable=False),
    sa.Column('unique_operators_count', sa.Integer(), nullable=False),
    sa.Column('avg_commands_count', sa.Float(), nullable=False),
    sa.Column('alarm_acknowledgements_count', sa.Integer(), nullable=False),
    sa.Column('maintenance_events_count', sa.Integer(), nullable=False),
    sa.Column('operational_hours', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['industrial_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_behavior_features_asset_id'), 'asset_behavior_features', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_behavior_features_window_size'), 'asset_behavior_features', ['window_size'], unique=False)
    op.create_table('department_behavior_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('window_size', sa.String(length=10), nullable=False),
    sa.Column('peak_activity_rate', sa.Float(), nullable=False),
    sa.Column('avg_users_online', sa.Float(), nullable=False),
    sa.Column('unique_assets_accessed_count', sa.Integer(), nullable=False),
    sa.Column('avg_network_usage', sa.Float(), nullable=False),
    sa.Column('typical_working_hours_ratio', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_behavior_features_department_id'), 'department_behavior_features', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_behavior_features_window_size'), 'department_behavior_features', ['window_size'], unique=False)
    op.create_table('user_behavior_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('window_size', sa.String(length=10), nullable=False),
    sa.Column('avg_session_duration', sa.Float(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('unique_devices_count', sa.Integer(), nullable=False),
    sa.Column('unique_assets_count', sa.Integer(), nullable=False),
    sa.Column('commands_per_hour', sa.Float(), nullable=False),
    sa.Column('weekend_activity_ratio', sa.Float(), nullable=False),
    sa.Column('night_activity_ratio', sa.Float(), nullable=False),
    sa.Column('remote_login_count', sa.Integer(), nullable=False),
    sa.Column('usb_usage_count', sa.Integer(), nullable=False),
    sa.Column('download_frequency', sa.Float(), nullable=False),
    sa.Column('config_change_count', sa.Integer(), nullable=False),
    sa.Column('failed_auth_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_behavior_features_user_id'), 'user_behavior_features', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_behavior_features_window_size'), 'user_behavior_features', ['window_size'], unique=False)
    op.create_table('device_behavior_features',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('window_size', sa.String(length=10), nullable=False),
    sa.Column('active_hours', sa.Float(), nullable=False),
    sa.Column('connected_users_count', sa.Integer(), nullable=False),
    sa.Column('avg_network_traffic_bytes', sa.Float(), nullable=False),
    sa.Column('config_change_count', sa.Integer(), nullable=False),
    sa.Column('firmware_change_count', sa.Integer(), nullable=False),
    sa.Column('maintenance_frequency', sa.Float(), nullable=False),
    sa.Column('unexpected_downtime_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_behavior_features_device_id'), 'device_behavior_features', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_behavior_features_window_size'), 'device_behavior_features', ['window_size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_behavior_features_window_size'), table_name='device_behavior_features')
    op.drop_index(op.f('ix_device_behavior_features_device_id'), table_name='device_behavior_features')
    op.drop_table('device_behavior_features')
    op.drop_index(op.f('ix_user_behavior_features_window_size'), table_name='user_behavior_features')
    op.drop_index(op.f('ix_user_behavior_features_user_id'), table_name='user_behavior_features')
    op.drop_table('user_behavior_features')
    op.drop_index(op.f('ix_department_behavior_features_window_size'), table_name='department_behavior_features')
    op.drop_index(op.f('ix_department_behavior_features_department_id'), table_name='department_behavior_features')
    op.drop_table('department_behavior_features')
    op.drop_index(op.f('ix_asset_behavior_features_window_size'), table_name='asset_behavior_features')
    op.drop_index(op.f('ix_asset_behavior_features_asset_id'), table_name='asset_behavior_features')
    op.drop_table('asset_behavior_features')
    op.drop_index(op.f('ix_behavior_snapshots_window_size'), table_name='behavior_snapshots')
    op.drop_index(op.f('ix_behavior_snapshots_timestamp'), table_name='behavior_snapshots')
    op.drop_index(op.f('ix_behavior_snapshots_entity_type'), table_name='behavior_snapshots')
    op.drop_index(op.f('ix_behavior_snapshots_entity_id'), table_name='behavior_snapshots')
    op.drop_table('behavior_snapshots')
    # ### end Alembic commands ###
