"""honeywell_alignment

Revision ID: bb60fdce46e9
Revises: 8e2e28097b46
Create Date: 2026-07-26 07:32:56.917706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb60fdce46e9'
down_revision: Union[str, None] = '8e2e28097b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('anomaly_classification', sa.String(length=50), nullable=True))
    op.add_column('devices', sa.Column('device_model', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('browser_fingerprint', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('tls_cert_id', sa.String(length=100), nullable=True))
    op.add_column('devices', sa.Column('protocol', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('auth_method', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('device_model', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('browser_fingerprint', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('tls_cert_id', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('os_version', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('firmware_version', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('mac_address', sa.String(length=17), nullable=True))
    op.add_column('events', sa.Column('session_duration', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('resource_accessed', sa.String(length=200), nullable=True))
    op.add_column('events', sa.Column('ground_truth_label', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'longitude')
    op.drop_column('users', 'latitude')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('events', 'ground_truth_label')
    op.drop_column('events', 'resource_accessed')
    op.drop_column('events', 'session_duration')
    op.drop_column('events', 'mac_address')
    op.drop_column('events', 'firmware_version')
    op.drop_column('events', 'os_version')
    op.drop_column('events', 'tls_cert_id')
    op.drop_column('events', 'browser_fingerprint')
    op.drop_column('events', 'device_model')
    op.drop_column('events', 'auth_method')
    op.drop_column('events', 'timezone')
    op.drop_column('events', 'longitude')
    op.drop_column('events', 'latitude')
    op.drop_column('events', 'city')
    op.drop_column('events', 'country')
    op.drop_column('devices', 'protocol')
    op.drop_column('devices', 'tls_cert_id')
    op.drop_column('devices', 'browser_fingerprint')
    op.drop_column('devices', 'device_model')
    op.drop_column('alerts', 'anomaly_classification')
    # ### end Alembic commands ###
